worker_processes auto;

events {
    worker_connections 1024;
}

stream {
    upstream matching_pool {
        least_conn;
        server matching-service-1:8443 max_fails=3 fail_timeout=10s;
        server matching-service-2:8443 max_fails=3 fail_timeout=10s;
        server matching-service-3:8443 max_fails=3 fail_timeout=10s;
    }

    server {
        listen 8443;
        proxy_pass matching_pool;
        proxy_connect_timeout 5s;
        proxy_timeout        60s;
    }
}
